### ISSUE TITLE
Almost Nothing works

### ISSUE THREAD

**Issue by deadspidervenom** [Wartori54/ImmersivePortalsSurvivalAdaptation#1]
Only thing i could get to work was the one way portal maker.

**Comment by Wartori54** [comment]
1. What version are you using (this mod, immersive portals and minecraft)?
2. Are you sure you're doing it right?
3. Do you have other mods installed?
4. Could you send a clip showing that it doesnt work.
5. If there's any error on the logs, can you send it?

**Comment by deadspidervenom** [comment]
At the time of the post 1.5, latest, 1.16.5
I am spawning them in creative and right clicking/Shift right clicking just like the one way portal maker
Yes plenty
This will take time but yes
No errors in the logs.

EDIT: just tested with 1.6 of your mod, can't change mode, but seems the modes are working.

**Comment by Wartori54** [comment]
In the creative inventory tab, you can see some items multiple times, that's because there are in different configurations.
The portal modificator has 4 modes: nothing, move, rotate and delete.
You can't change the mode with shift-right click, you have to combine it with the addons, it's explained here: [https://github.com/Wartori54/ImmersivePortalsSurvivalAdaptation/wiki/Recipes#recipies-that-change-nbt](https://github.com/Wartori54/ImmersivePortalsSurvivalAdaptation/wiki/Recipes#recipies-that-change-nbt),
Shift-right click is only used in the delete mode, to choose with faces will be deleted.
It's also used in the portal creator to change the portal size, and for  the portal completer to choose with faces will be completed

**Comment by Wartori54** [comment]
Closing this as 16 days has passed and no response
